# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureConnection'
    subscriptionId: '99ed60c8-1564-4d21-8341-bc7728730bf8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMRG'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/arifkhan1786/azuredevopslab/main/azuredeploy.json.txt'
    overrideParameters: '-projectName ARIFARMDEO1'
    deploymentMode: 'Incremental'
  displayName: 'Run a multi-line script'
